
[package]
name = "gaiaci"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
mlua = { version = "0.10.5", features = ["lua54", "vendored", "serialize", "async"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "time"] }
chrono = "0.4"
once_cell = "1.18.0"
regex = "1.11.1"

[dev-dependencies]
assert_cmd = "2.0"
tempfile = "3.10"
predicates = "3.1"
once_cell = "1.18.0"
